# Generated by Django 4.2.10 on 2024-02-12 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20240212_0641'),
        ('store', '0003_product_image'),
    ]

    operations = [
    ]
