# Generated by Django 4.2.10 on 2024-02-12 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_customer_id_alter_order_id_alter_orderitem_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='data_ordered',
            new_name='date_ordered',
        ),
    ]
