# Generated by Django 4.2.10 on 2024-02-12 21:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_rename_data_ordered_order_date_ordered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.CharField(default=datetime.datetime(2024, 2, 12, 21, 26, 38, 496179, tzinfo=datetime.timezone.utc), max_length=200),
            preserve_default=False,
        ),
    ]
