# Generated by Django 4.2.10 on 2024-02-12 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_rename_name_product_product_name_alter_customer_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Product_name',
            new_name='name',
        ),
    ]
