# Generated by Django 4.2.10 on 2024-02-19 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_rename_date_ordered_order_data_ordered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='transaction_id',
        ),
    ]
