# Generated by Django 4.2.10 on 2024-02-19 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_rename_data_ordered_order_date_ordered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(blank=True, default=123456, max_length=200),
            preserve_default=False,
        ),
    ]
